import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { farsi } from "@/lib/fonts";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dari Calendar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={farsi.className}>{children}</body>
    </html>
  );
}
